### ISSUE TITLE
 sound drive for hp elitebook 8470p

### ISSUE THREAD

**Issue by orotenrandy6** [SkyrilHD/HP-8x70W-Hackintosh#29]
please please any one help me to install sound drive for hp elitebook 8470p ,it is urgent please 

![Screen Shot 2023-11-07 at 23 20 43](https://github.com/SkyrilHD/HP-8x70W-Hackintosh/assets/150198013/55721259-bb2b-4ffe-b394-764c68df2fa1)
![Screen Shot 2023-11-07 at 23 22 07](https://github.com/SkyrilHD/HP-8x70W-Hackintosh/assets/150198013/a68d1d1a-b85a-4515-92d8-e3c09dc89c83)

**Comment by SkyrilHD** [comment]
Update AppleALC to 1.8.7 and use layout-id 76. Also check the correct audio PCI path

**Comment by orotenrandy6** [comment]
> Update AppleALC to 1.8.7 and use layout-id 76. Also check the correct audio PCI path
sir thank you for your reply ,but I am a new user can you tell me how to do this in easy way ?

**Comment by SkyrilHD** [comment]
For updating, [download](https://github.com/acidanthera/AppleALC/releases) the latest release from the AppleALC repo. Replace your current AppleALC kext found in OC/Kexts with the newest one.

For correcting the audio PCI path, read this guide: https://dortania.github.io/OpenCore-Post-Install/universal/audio.html
